#!/usr/bin/env bash

ROOT_DIR=$(cd "$(dirname `realpath $0`)"; pwd)

export HOROVOD_LOG_LEVEL=TRACE

export http_proxy=http://dl-proxy.service.163.org:8123
export https_proxy=http://dl-proxy.service.163.org:8123

#python $ROOT_DIR/tensorflow_boston.py
#python $ROOT_DIR/pytorch_mnist.py
#python $ROOT_DIR/mxnet_mnist.py
python $ROOT_DIR/tensorflow_broadcast.py
